# entirely generated by chat gpt last minute, tests if reservation page loads successfully

from django.test import TestCase
from django.urls import reverse
from django.contrib.auth.models import User

class ReservationPageLoadTest(TestCase):
    def setUp(self):
        # create a user to satisfy login_required
        self.user = User.objects.create_user(username="test", password="pass1234")

    def test_reservation_page_loads(self):
        # Log the user in
        self.client.login(username="test", password="pass1234")

        # Visit the reservation creation page
        url = reverse("reservation:create_reservation")
        response = self.client.get(url)

        # Should return OK
        self.assertEqual(response.status_code, 200)

        # Template should contain heading text
        self.assertContains(response, "Make a Reservation")
